In [87]:
import pandas as pd

def korea_bank(col_name, code, item_code1='?', item_code2='?'):
  key = '**********'
  data_start = '1'
  data_end= '1000'
  # code = '080Y111' 
  cycle = 'MM'
  search_start = '201801'
  search_end = '202108'
  # item_code1 = 'I32AL3'
  # item_code2 = 'I11B'
  url = f'http://ecos.bok.or.kr/api/StatisticSearch/{key}/json/kr/{data_start}/{data_end}/{code}/{cycle}/{search_start}/{search_end}/{item_code1}/{item_code2}'
  res = requests.get(url)
  data = res.json()
  data = data['StatisticSearch']['row']
  df = pd.DataFrame(data).set_index('TIME')
  df = df[['DATA_VALUE']]
  df.rename(columns={df.columns[0]:col_name},inplace=True)
  return df

korea_bank('가동률지수','080Y111','I32AL3','I11B') # 제조업생산능력및가동률지수/시멘트,석회,플라스터및그제품제조업/가동률지수(원지수)

        가동률지수
TIME
201801   78.6
201802   74.1
201803  116.6
201804  120.9
201805  124.6
201806  126.8
201807  112.3
201808     99
201809  101.1
201810  122.2
201811    122
201812  102.5
201901   90.7
201902     72
201903  107.8
201904  115.1
201905  116.2
201906  111.6
201907  104.2
201908   99.4
201909   84.4
201910  109.3
201911  112.3
201912  103.8
202001   72.5
202002   78.3
202003  100.8
202004  105.3
202005   94.6
202006    100
202007   87.6
202008     78
202009   95.4
202010  101.1
202011  105.1
202012  101.5
202101   73.4
202102   77.8
202103  114.4
202104  115.6
202105    106
202106  108.9
202107  104.6
202108   93.7

In [88]:
korea_bank('건축착공면적','085Y136','1') # 건축물착공현황,연면적

          건축착공면적
TIME
201801   8213988
201802   6982354
201803  13431681
201804  11498313
201805  13370763
...          ...
202103   3267387
202104   2577832
202105   2230913
202106   1928657
202107   2069401

[473 rows x 1 columns]

In [92]:
korea_bank('건설수주','080Y017','I42A') # 국내건설수주액/총수주액

            건설수주
TIME
201801  12950041
201802   9460014
201803  11827179
201804   9244402
201805  13674960
201806  11336474
201807  10618035
201808   9100838
201809  10694335
201810  10718279
201811  11924951
201812  21742503
201901   9354316
201902   7769343
201903  16252241
201904  12669551
201905  10025314
201906  11286381
201907   8176838
201908   8400443
201909  14366040
201910  15256861
201911  13752803
201912  26932542
202001  10100506
202002  10747545
202003  12140037
202004   8620368
202005  13659839
202006  20237937
202007  15335812
202008  12501220
202009  15469918
202010  13898995
202011  17702517
202012  29181854
202101  12852091
202102  12621360
202103  16514305
202104  17845882
202105  14740418
202106  17383659
202107  14448672
202108  15355137

In [93]:
korea_bank('미분양현황','085Y039','I410A') # 미분양주택현황/전국 (자료조사.xlsx파일이랑 수치 차이 있음/자료조사.xlsx의 미분양현황은 출처 - kosis)

        미분양현황
TIME
201801  59104
201802  60903
201803  58004
201804  59583
201805  59836
201806  62050
201807  63132
201808  62370
201809  60596
201810  60502
201811  60122
201812  58838
201901  59162
201902  59614
201903  62147
201904  62041
201905  62741
201906  63705
201907  62529
201908  62385
201909  60062
201910  56098
201911  53561
201912  47797
202001  43268
202002  39456
202003  38304
202004  36629
202005  33894
202006  29262
202007  28883
202008  28831
202009  28309
202010  26703
202011  23620
202012  19005
202101  17130
202102  15786
202103  15270
202104  15798
202105  15660
202106  16289
202107  15198
202108  14864